AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFront template

Parameters:
  BucketName:
    Type: String
    Description: S3 Bucket Name
  DomainName:
    Type: String
    Description: Altername Domain Name
  ACMArn:
    Type: String
    Description: ACM Arn

Resources:
  # CloudFrontのキャッシュポリシーの作成
  cfnCloudFrontCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        DefaultTTL: 86400
        MaxTTL: 86400
        MinTTL: 86400
        Name: "cfn-cloudfront-cache-policy"
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: "none"
          EnableAcceptEncodingGzip: false
          HeadersConfig:
            HeaderBehavior: "none"
          QueryStringsConfig:
            QueryStringBehavior: "none"

  # CloudFrontのOACの設定
  cfnCloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: "cfn-cloudfront-origin-access-control"
        OriginAccessControlOriginType: "s3"
        SigningBehavior: "always"
        SigningProtocol: "sigv4"

  # CloudFrontディストリビューションの作成
  cfnCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: !Ref cfnCloudFrontCachePolicy
          Compress: false
          SmoothStreaming: false
          TargetOriginId: !Sub ${BucketName}.s3.ap-northeast-1.amazonaws.com
          ViewerProtocolPolicy: "allow-all"
        DefaultRootObject: "index.html"
        Enabled: true
        IPV6Enabled: false
        Origins:
          - DomainName: !Sub ${BucketName}.s3.ap-northeast-1.amazonaws.com
            Id: !Sub ${BucketName}.s3.ap-northeast-1.amazonaws.com
            OriginAccessControlId: !Ref cfnCloudFrontOriginAccessControl
            OriginPath: "/angular-project-frontend"
            S3OriginConfig:
              OriginAccessIdentity: ""
        PriceClass: "PriceClass_200"
        Staging: false
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMArn
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
      Tags:
        - Key: "Name"
          Value: "cfn-cloudfront"

  # バケットポリシー更新
  cfnS3BucketPolicyForCloudFront:
    Type: AWS::S3::BucketPolicy
    DependsOn: cfnCloudFrontDistribution
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Version: "2008-10-17"
        Statement:
          - Sid: "AllowCloudFrontServicePrincipal"
            Effect: "Allow"
            Principal:
              Service:
                - "cloudfront.amazonaws.com"
            Action:
              - "s3:GetObject"
            Resource:
              - !Sub "arn:aws:s3:::${BucketName}/*"
            Condition:
              StringEquals:
                AWS:SourceArn:
                  - !Join
                    - ""
                    - - !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/"
                      - !Ref cfnCloudFrontDistribution
Outputs:
  DistributionID:
    Value: !Ref cfnCloudFrontDistribution
    Description: CloudFront Distribution ID
